// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentMaq.Infrastructure.Persistence;

#nullable disable

namespace RentMaq.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RentMaqDbContext))]
    [Migration("20260407234758_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "alert_type_enum", new[] { "fault_code", "impact", "tilt", "overtemp", "overpressure", "geofence_breach" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing_model_enum", new[] { "fixed_period", "hourly_usage", "tiered", "shift_based" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "contract_status_enum", new[] { "draft", "reserved", "active", "suspended_maintenance", "returning", "inspection", "overdue", "in_dispute", "closed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "damage_attribution_enum", new[] { "normal_wear", "tenant_attributable", "environmental", "pre_existing", "under_dispute" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "equipment_status_enum", new[] { "available", "rented", "in_maintenance", "decommissioned" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "equipment_type_enum", new[] { "miniexcavator", "skid_steer", "scissor_lift", "boom_lift", "compactor", "generator", "pump" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "maintenance_order_type_enum", new[] { "preventive", "corrective", "inspection" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "severity_enum", new[] { "info", "warning", "critical", "shutdown" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "work_order_status_enum", new[] { "pending", "in_progress", "loto_applied", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentMaq.Domain.Entities.CfdiDocument", b =>
                {
                    b.Property<Guid>("CfdiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cfdi_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("cancel_reason");

                    b.Property<string>("CancellationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cancellation_status");

                    b.Property<string>("CfdiType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("cfdi_type");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("forma_pago");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PacProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pac_provider");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pdf_url");

                    b.Property<Guid?>("RelatedCfdiId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_cfdi_id");

                    b.Property<string>("RelationType")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("relation_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("UsoCfdi")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("uso_cfdi");

                    b.Property<Guid?>("UuidFiscal")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid_fiscal");

                    b.Property<string>("XmlUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("xml_url");

                    b.HasKey("CfdiId");

                    b.HasIndex("ContractId");

                    b.HasIndex("RelatedCfdiId");

                    b.HasIndex("UuidFiscal")
                        .IsUnique();

                    b.ToTable("cfdi_documents", null, t =>
                        {
                            t.HasCheckConstraint("chk_cfdi_status", "status IN ('TIMBRADO','CANCELADO','PENDIENTE_PAGO','PAGADO')");

                            t.HasCheckConstraint("chk_cfdi_type", "cfdi_type IN ('I','E','P')");

                            t.HasCheckConstraint("chk_payment_method", "payment_method IN ('PUE','PPD')");
                        });
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.DamageAssessment", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessor_id");

                    b.Property<int>("Attribution")
                        .HasColumnType("integer")
                        .HasColumnName("attribution");

                    b.Property<Guid?>("ChecklistId")
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CustomerSignatureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_signature_url");

                    b.Property<string>("DamageDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("damage_description");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<decimal?>("EstimatedRepairCost")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("estimated_repair_cost");

                    b.Property<Guid?>("FaultEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("fault_event_id");

                    b.Property<DateTimeOffset>("InspectionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inspection_date");

                    b.Property<string>("Photos")
                        .HasColumnType("jsonb")
                        .HasColumnName("photos");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("AssessmentId");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("ContractId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("FaultEventId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("damage_assessments", null, t =>
                        {
                            t.HasCheckConstraint("chk_damage_status", "status IN ('DRAFT','UNDER_REVIEW','APPROVED_FOR_CHARGE','DISMISSED')");
                        });
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.Deposit", b =>
                {
                    b.Property<Guid>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("deposit_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountingClassification")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("LIABILITY")
                        .HasColumnName("accounting_classification");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AppliedAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("applied_amount");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<decimal>("RefundedAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("refunded_amount");

                    b.Property<Guid?>("RelatedCfdiId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_cfdi_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("DepositId");

                    b.HasIndex("ContractId");

                    b.HasIndex("RelatedCfdiId");

                    b.ToTable("deposits", null, t =>
                        {
                            t.HasCheckConstraint("chk_accounting_class", "accounting_classification IN ('LIABILITY','RECOGNIZED_INCOME')");

                            t.HasCheckConstraint("chk_deposit_balance", "applied_amount + refunded_amount <= amount");

                            t.HasCheckConstraint("chk_deposit_status", "status IN ('PENDING_COLLECTION','HELD_AS_LIABILITY','PARTIALLY_APPLIED','FULLY_APPLIED','REFUNDED')");
                        });
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AcquisitionCost")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("acquisition_cost");

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date")
                        .HasColumnName("acquisition_date");

                    b.Property<string>("AempEndpointUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("aemp_endpoint_url");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("asset_tag");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("current_status");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type");

                    b.Property<Guid?>("LoadProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("load_profile_id");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("WeightTons")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_tons");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("EquipmentId");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("LoadProfileId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.EquipmentCertification", b =>
                {
                    b.Property<Guid>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("certification_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("BlocksRental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("blocks_rental");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("certification_name");

                    b.Property<string>("CertificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("certification_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("document_url");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issued_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("CertificationId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("equipment_certifications", null, t =>
                        {
                            t.HasCheckConstraint("chk_cert_status", "status IN ('VALID','EXPIRED','REVOKED')");
                        });
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.EquipmentLoadProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<decimal>("EngineLoadFactor")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("engine_load_factor");

                    b.Property<string>("EquipmentMake")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("equipment_make");

                    b.Property<string>("EquipmentModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("equipment_model");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("MaintenanceIntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_interval_hours");

                    b.Property<decimal>("PtoLoadFactor")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("pto_load_factor");

                    b.Property<decimal?>("TargetUtilizationPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("target_utilization_pct");

                    b.HasKey("ProfileId");

                    b.HasIndex("EquipmentMake", "EquipmentModel", "ApplicationType")
                        .IsUnique();

                    b.ToTable("equipment_load_profiles", (string)null);
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.EquipmentThreshold", b =>
                {
                    b.Property<Guid>("ThresholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("threshold_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("CriticalValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("critical_value");

                    b.Property<string>("EquipmentModel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("equipment_model");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type");

                    b.Property<decimal?>("ShutdownValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("shutdown_value");

                    b.Property<string>("ThresholdType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("threshold_type");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<decimal?>("WarningValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("warning_value");

                    b.HasKey("ThresholdId");

                    b.HasIndex("EquipmentType", "EquipmentModel", "ThresholdType")
                        .IsUnique();

                    b.ToTable("equipment_thresholds", (string)null);
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.ExtraordinaryCharge", b =>
                {
                    b.Property<Guid>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountDirectBill")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("amount_direct_bill");

                    b.Property<decimal>("AmountFromDeposit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("amount_from_deposit");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<Guid?>("CfdiId")
                        .HasColumnType("uuid")
                        .HasColumnName("cfdi_id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("DepositId")
                        .HasColumnType("uuid")
                        .HasColumnName("deposit_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("ChargeId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CfdiId");

                    b.HasIndex("ContractId");

                    b.HasIndex("DepositId");

                    b.ToTable("extraordinary_charges", null, t =>
                        {
                            t.HasCheckConstraint("chk_charge_status", "status IN ('DETECTED','ATTRIBUTED','APPLIED_TO_DEPOSIT','INVOICED')");
                        });
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.Geofence", b =>
                {
                    b.Property<Guid>("GeofenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("geofence_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsYard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_yard");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Geometry>("Perimeter")
                        .IsRequired()
                        .HasColumnType("geography(polygon, 4326)")
                        .HasColumnName("perimeter");

                    b.HasKey("GeofenceId");

                    b.ToTable("geofences", (string)null);
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.InspectionChecklist", b =>
                {
                    b.Property<Guid>("ChecklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChecklistItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("checklist_items");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<decimal?>("FuelLevelPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fuel_level_pct");

                    b.Property<decimal?>("HorometerReading")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("horometer_reading");

                    b.Property<DateTimeOffset>("InspectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inspected_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inspection_type");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspector_id");

                    b.Property<string>("OverallResult")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("overall_result");

                    b.Property<string>("Photos")
                        .HasColumnType("jsonb")
                        .HasColumnName("photos");

                    b.HasKey("ChecklistId");

                    b.HasIndex("ContractId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("inspection_checklists", null, t =>
                        {
                            t.HasCheckConstraint("chk_inspection_type", "inspection_type IN ('PRE_DELIVERY','POST_RETURN')");

                            t.HasCheckConstraint("chk_overall_result", "overall_result IN ('APPROVED','APPROVED_WITH_OBSERVATIONS','REJECTED')");
                        });
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.MaintenanceSchedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<int?>("IntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("interval_hours");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateOnly?>("LastServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("last_service_date");

                    b.Property<decimal?>("LastServiceHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("last_service_hours");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date")
                        .HasColumnName("next_due_date");

                    b.Property<decimal?>("NextDueHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("next_due_hours");

                    b.Property<string>("ServiceTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_tier");

                    b.HasKey("ScheduleId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("maintenance_schedules", (string)null);
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.MaintenanceWorkOrder", b =>
                {
                    b.Property<Guid>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<DateOnly>("ExecutionDate")
                        .HasColumnType("date")
                        .HasColumnName("execution_date");

                    b.Property<decimal?>("LaborHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("labor_hours");

                    b.Property<Guid?>("LinkedAlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_alert_id");

                    b.Property<bool>("LotoApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("loto_applied");

                    b.Property<DateTimeOffset?>("LotoAppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loto_applied_at");

                    b.Property<int>("LotoTimeoutHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24)
                        .HasColumnName("loto_timeout_hours");

                    b.Property<DateOnly?>("NextServiceDueAt")
                        .HasColumnType("date")
                        .HasColumnName("next_service_due_at");

                    b.Property<decimal?>("NextServiceDueHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("next_service_due_hours");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer")
                        .HasColumnName("order_type");

                    b.Property<string>("PartsUsed")
                        .HasColumnType("jsonb")
                        .HasColumnName("parts_used");

                    b.Property<Guid?>("PerformedByWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_worker_id");

                    b.Property<bool>("ProtectorsReinstalled")
                        .HasColumnType("boolean")
                        .HasColumnName("protectors_reinstalled");

                    b.Property<DateTimeOffset?>("ProtectorsVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("protectors_verified_at");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text")
                        .HasColumnName("technician_notes");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_cost");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("trigger_source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("LinkedAlertId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("Status");

                    b.HasIndex("EquipmentId", "ExecutionDate");

                    b.ToTable("maintenance_work_orders", null, t =>
                        {
                            t.HasCheckConstraint("chk_trigger_source", "trigger_source IN ('TELEMETRY_AUTO','CALENDAR_AUTO','MANUAL_INSPECTION','TENANT_REPORT')");
                        });
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.OperatorCertification", b =>
                {
                    b.Property<Guid>("OperatorCertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("operator_cert_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Dc3CertificateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dc3_certificate_number");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("document_url");

                    b.Property<int>("EquipmentTypeCertified")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_certified");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("expires_at");

                    b.Property<DateOnly>("IssuedAt")
                        .HasColumnType("date")
                        .HasColumnName("issued_at");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operator_name");

                    b.HasKey("OperatorCertId");

                    b.HasIndex("ContractId");

                    b.ToTable("operator_certifications", (string)null);
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.RentalContract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("BaseMonthlyRate")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("base_monthly_rate");

                    b.Property<int>("BillingModel")
                        .HasColumnType("integer")
                        .HasColumnName("billing_model");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("DailyRate")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("daily_rate");

                    b.Property<string>("DepositType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deposit_type");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid?>("GeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("geofence_id");

                    b.Property<string>("InsurancePolicyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("insurance_policy_number");

                    b.Property<int?>("MaxHoursIncluded")
                        .HasColumnType("integer")
                        .HasColumnName("max_hours_included");

                    b.Property<decimal?>("OvertimeMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overtime_multiplier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("WeeklyRate")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("weekly_rate");

                    b.HasKey("ContractId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("GeofenceId");

                    b.HasIndex("TenantId");

                    b.ToTable("rental_contracts", (string)null);
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.TelemetryAlert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Acknowledged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("acknowledged");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by");

                    b.Property<decimal?>("ActualValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("actual_value");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<bool>("AttributedToTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("attributed_to_tenant");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<int?>("Fmi")
                        .HasColumnType("integer")
                        .HasColumnName("fmi");

                    b.Property<decimal?>("ImpactGX")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("impact_g_x");

                    b.Property<decimal?>("ImpactGY")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("impact_g_y");

                    b.Property<decimal?>("ImpactGZ")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("impact_g_z");

                    b.Property<bool>("Resolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("resolved");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<int?>("Spn")
                        .HasColumnType("integer")
                        .HasColumnName("spn");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("threshold_value");

                    b.Property<decimal?>("TiltLateralDeg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tilt_lateral_deg");

                    b.Property<decimal?>("TiltLongitudinalDeg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tilt_longitudinal_deg");

                    b.HasKey("AlertId");

                    b.HasIndex("DetectedAt")
                        .IsDescending();

                    b.HasIndex("EquipmentId", "Severity", "Resolved");

                    b.ToTable("telemetry_alerts", (string)null);
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.TelemetryReading", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ActiveSwitches")
                        .HasColumnType("jsonb")
                        .HasColumnName("active_switches");

                    b.Property<decimal?>("Altitude")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("altitude");

                    b.Property<decimal?>("AmbientTemperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ambient_temperature");

                    b.Property<decimal?>("CumulativeIdleHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cumulative_idle_hours");

                    b.Property<decimal?>("CumulativeIdleNonOperatingHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cumulative_idle_non_operating_hours");

                    b.Property<decimal?>("DefLevel")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("def_level");

                    b.Property<decimal?>("DefUsed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("def_used");

                    b.Property<decimal?>("Distance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("distance");

                    b.Property<decimal?>("EngineHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("engine_hours");

                    b.Property<int?>("EngineStatus")
                        .HasColumnType("integer")
                        .HasColumnName("engine_status");

                    b.Property<decimal?>("EngineTemperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("engine_temperature");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<decimal?>("FuelLevel")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fuel_level");

                    b.Property<decimal?>("FuelUsed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fuel_used");

                    b.Property<decimal?>("Hdop")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("hdop");

                    b.Property<decimal?>("Heading")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("heading");

                    b.Property<decimal?>("HydraulicPressure")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hydraulic_pressure");

                    b.Property<decimal?>("IdleHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("idle_hours");

                    b.Property<decimal?>("ImpactGX")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("impact_g_x");

                    b.Property<decimal?>("ImpactGY")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("impact_g_y");

                    b.Property<decimal?>("ImpactGZ")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("impact_g_z");

                    b.Property<decimal?>("LoadFactor")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("load_factor");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(point, 4326)")
                        .HasColumnName("location");

                    b.Property<decimal?>("PtoHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pto_hours");

                    b.Property<int?>("Satellites")
                        .HasColumnType("integer")
                        .HasColumnName("satellites");

                    b.Property<decimal?>("SpeedKmh")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("speed_kmh");

                    b.Property<decimal?>("TiltLateral")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tilt_lateral");

                    b.Property<decimal?>("TiltLongitudinal")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tilt_longitudinal");

                    b.HasKey("SnapshotId", "RecordedAt");

                    b.HasIndex("EquipmentId");

                    b.ToTable("telemetry_readings", (string)null);
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("CreditStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDING_EVALUATION")
                        .HasColumnName("credit_status");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("legal_name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("rfc");

                    b.Property<string>("TaxRegime")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("tax_regime");

                    b.Property<string>("UsoCfdiDefault")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasDefaultValue("G03")
                        .HasColumnName("uso_cfdi_default");

                    b.HasKey("TenantId");

                    b.HasIndex("Rfc")
                        .IsUnique();

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("chk_credit_status", "credit_status IN ('PENDING_EVALUATION','APPROVED','SUSPENDED','BLOCKED')");
                        });
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.CfdiDocument", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.RentalContract", "Contract")
                        .WithMany("CfdiDocuments")
                        .HasForeignKey("ContractId");

                    b.HasOne("RentMaq.Domain.Entities.CfdiDocument", "RelatedCfdi")
                        .WithMany()
                        .HasForeignKey("RelatedCfdiId");

                    b.Navigation("Contract");

                    b.Navigation("RelatedCfdi");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.DamageAssessment", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.InspectionChecklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("ChecklistId");

                    b.HasOne("RentMaq.Domain.Entities.RentalContract", "Contract")
                        .WithMany("DamageAssessments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentMaq.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentMaq.Domain.Entities.TelemetryAlert", "FaultEvent")
                        .WithMany()
                        .HasForeignKey("FaultEventId");

                    b.HasOne("RentMaq.Domain.Entities.MaintenanceWorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId");

                    b.Navigation("Checklist");

                    b.Navigation("Contract");

                    b.Navigation("Equipment");

                    b.Navigation("FaultEvent");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.Deposit", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.RentalContract", "Contract")
                        .WithMany("Deposits")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentMaq.Domain.Entities.CfdiDocument", "RelatedCfdi")
                        .WithMany()
                        .HasForeignKey("RelatedCfdiId");

                    b.Navigation("Contract");

                    b.Navigation("RelatedCfdi");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.EquipmentLoadProfile", "LoadProfile")
                        .WithMany()
                        .HasForeignKey("LoadProfileId");

                    b.Navigation("LoadProfile");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.EquipmentCertification", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.Equipment", "Equipment")
                        .WithMany("Certifications")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.ExtraordinaryCharge", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.DamageAssessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("AssessmentId");

                    b.HasOne("RentMaq.Domain.Entities.CfdiDocument", "Cfdi")
                        .WithMany()
                        .HasForeignKey("CfdiId");

                    b.HasOne("RentMaq.Domain.Entities.RentalContract", "Contract")
                        .WithMany("ExtraordinaryCharges")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentMaq.Domain.Entities.Deposit", "Deposit")
                        .WithMany()
                        .HasForeignKey("DepositId");

                    b.Navigation("Assessment");

                    b.Navigation("Cfdi");

                    b.Navigation("Contract");

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.InspectionChecklist", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.RentalContract", "Contract")
                        .WithMany("InspectionChecklists")
                        .HasForeignKey("ContractId");

                    b.HasOne("RentMaq.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.MaintenanceSchedule", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.Equipment", "Equipment")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.MaintenanceWorkOrder", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.Equipment", "Equipment")
                        .WithMany("WorkOrders")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentMaq.Domain.Entities.TelemetryAlert", "LinkedAlert")
                        .WithMany()
                        .HasForeignKey("LinkedAlertId");

                    b.HasOne("RentMaq.Domain.Entities.MaintenanceSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Equipment");

                    b.Navigation("LinkedAlert");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.OperatorCertification", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.RentalContract", "Contract")
                        .WithMany("OperatorCertifications")
                        .HasForeignKey("ContractId");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.RentalContract", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentMaq.Domain.Entities.Geofence", "Geofence")
                        .WithMany()
                        .HasForeignKey("GeofenceId");

                    b.HasOne("RentMaq.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Contracts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Geofence");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.TelemetryAlert", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.Equipment", "Equipment")
                        .WithMany("TelemetryAlerts")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.TelemetryReading", b =>
                {
                    b.HasOne("RentMaq.Domain.Entities.Equipment", "Equipment")
                        .WithMany("TelemetryReadings")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("MaintenanceSchedules");

                    b.Navigation("TelemetryAlerts");

                    b.Navigation("TelemetryReadings");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.RentalContract", b =>
                {
                    b.Navigation("CfdiDocuments");

                    b.Navigation("DamageAssessments");

                    b.Navigation("Deposits");

                    b.Navigation("ExtraordinaryCharges");

                    b.Navigation("InspectionChecklists");

                    b.Navigation("OperatorCertifications");
                });

            modelBuilder.Entity("RentMaq.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
